name: Mirror to Gitea

on:
  push:
    branches: ["**"]
    tags: ["**"]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror repository
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          git clone --mirror https://x-access-token:${{ github.token }}@github.com/${{ github.repository }} repo.git
          cd repo.git

          git remote set-url origin https://reallynniroprobably:$GITEA_TOKEN@chookspace.com/reallynniroprobably/iodine.git

          git push --mirror
